# Proyecto

### Importación de librerías.

In [8]:
import pandas as pd
import folium
from folium.plugins import HeatMap

### Extracción y visualización previa de los datos.

In [9]:
df_datos = pd.read_csv('datos_limpios.csv')
df_estacion = pd.read_csv('estaciones.csv')

C:\Users\ricro\AppData\Local\Temp\ipykernel_28732\2580204213.py:1: DtypeWarning: Columns (0,2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_datos = pd.read_csv('datos_limpios.csv')

In [10]:
df_datos.head(2)

  Ciclo_Estacion_Retiro Fecha_Retiro Ciclo_Estacion_Arribo
0                    52   2015-03-29                    35
1                    52   2015-03-29                    35

In [11]:
df_estacion.head(2)

,station_id,external_id,name,short_name,lat,lon,capacity,rental_methods,electric_bike_surcharge_waiver,is_charging,eightd_has_key_dispenser,has_kiosk,source_last_updated_unix,source_last_updated_utc,source_ttl_seconds
0,1,e961269c-34c4-4b70-8e30-a51aa95a8429,CE-710 Molino del Rey - Glorieta de la Lealtad,710,19.416795,-99.192508,39,KEY|CREDITCARD,False,False,False,True,1775875064,2026-04-11T02:37:44+00:00,10
1,5,3ea89109-d2f3-46eb-9c41-c43742050340,CE-407 Prolongación Xochicalco-General Emilia...,407,19.367266,-99.158656,19,KEY|CREDITCARD,False,False,False,True,1775875064,2026-04-11T02:37:44+00:00,10

### Selección de las columnas necesarias para el análisis.

In [15]:
df_estacion = df_estacion[['short_name', 'lat', 'lon']]