In [1]:
import pandas as pd

### 2015

In [3]:
df_2015_1 = pd.read_csv('DATOS/2015-03.csv', low_memory=False)
df_2015_2 = pd.read_csv('DATOS/2015-04.csv', low_memory=False)

In [4]:
df_2015_1.head(2)

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_Estacion_Arribo,Fecha_Arribo,Hora_Arribo
0,M,30,0725,146,2015-03-01,00:00:32.617000,156,2015-03-01,00:09:32
1,M,26,0575,59,2015-03-01,00:00:33.460000,59,2015-03-01,00:15:26.723000

In [5]:
df_2015_2.head(2)

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_Estacion_Arribo,Fecha_Arribo,Hora_Arribo
0,M,32,3438,73,2015-04-01,00:00:02.850000,181,2015-04-01,00:04:46
1,M,31,4031,74,2015-04-01,00:00:19.463000,285,2015-04-01,00:09:00.437000

In [6]:
df_2015_1['Fecha_Retiro'] = pd.to_datetime(df_2015_1['Fecha_Retiro'])
df_2015_1 = df_2015_1[((df_2015_1['Fecha_Retiro'] >= pd.Timestamp('2015-03-29')) & (df_2015_1['Fecha_Retiro'] <= pd.Timestamp('2015-04-05')))]

In [18]:
df_2015_2['Fecha_Retiro'] = pd.to_datetime(df_2015_2['Fecha_Retiro'])
df_2015_2 = df_2015_2[((df_2015_2['Fecha_Retiro'] >= pd.Timestamp('2015-03-29')) & (df_2015_2['Fecha_Retiro'] <= pd.Timestamp('2015-04-05')))]

In [20]:
df_2015 = pd.concat([df_2015_1, df_2015_2])

In [22]:
df_2015.info()

<class 'pandas.core.frame.DataFrame'>
Index: 140819 entries, 744480 to 646969
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Genero_Usuario         140819 non-null  object
 1   Edad_Usuario           140819 non-null  int64
 2   Bici                   140819 non-null  object
 3   Ciclo_Estacion_Retiro  140819 non-null  int64
 4   Fecha_Retiro           140819 non-null  datetime64[ns]
 5   Hora_Retiro            140819 non-null  object
 6   Ciclo_Estacion_Arribo  140819 non-null  int64
 7   Fecha_Arribo           140819 non-null  object
 8   Hora_Arribo            140819 non-null  object
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 10.7+ MB

In [24]:
del df_2015_1
del df_2015_2

### 2016

In [27]:
df_2016 = pd.read_csv('DATOS/2016-03.csv', low_memory=False)

In [28]:
df_2016.head(2)

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_Estacion_Arribo,Fecha_Arribo,Hora_Arribo
0,M,26,4797,435,2016-03-01,00:00:05.010000,373,2016-03-01,00:08:56
1,M,39,0040,48,2016-03-01,00:00:16.990000,110,2016-03-01,00:07:13.400000

In [29]:
df_2016['Fecha_Retiro'] = pd.to_datetime(df_2016['Fecha_Retiro'])
df_2016 = df_2016[((df_2016['Fecha_Retiro'] >= pd.Timestamp('2016-03-20')) & 
                       (df_2016['Fecha_Retiro'] <= pd.Timestamp('2016-03-27')))]

In [30]:
df_2016.info()

<class 'pandas.core.frame.DataFrame'>
Index: 109237 entries, 481599 to 713410
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Genero_Usuario         109237 non-null  object
 1   Edad_Usuario           109237 non-null  int64
 2   Bici                   109237 non-null  object
 3   Ciclo_Estacion_Retiro  109237 non-null  int64
 4   Fecha_Retiro           109237 non-null  datetime64[ns]
 5   Hora_Retiro            109237 non-null  object
 6   Ciclo_Estacion_Arribo  109237 non-null  int64
 7   Fecha_Arribo           109237 non-null  object
 8   Hora_Arribo            109237 non-null  object
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 8.3+ MB

### 2017

In [32]:
df_2017 = pd.read_csv('DATOS/2017-04.csv', low_memory=False)

In [33]:
df_2017.head(2)

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_Estacion_Arribo,Fecha_Arribo,Hora_Arribo
0,M,22,3834,278,01/04/2017,0:00:09,375,01/04/2017,0:16:05
1,M,35,8435,69,01/04/2017,0:00:12,62,01/04/2017,0:08:07

In [34]:
df_2017['Fecha_Retiro'] = pd.to_datetime(df_2017['Fecha_Retiro'], format='%d/%m/%Y', errors='coerce')
df_2017 = df_2017[((df_2017['Fecha_Retiro'] >= pd.Timestamp('2017-04-09')) & 
                       (df_2017['Fecha_Retiro'] <= pd.Timestamp('2017-04-16')))]

In [35]:
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 137354 entries, 181632 to 609301
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Genero_Usuario         137354 non-null  object
 1   Edad_Usuario           137354 non-null  int64
 2   Bici                   137354 non-null  int64
 3   Ciclo_Estacion_Retiro  137354 non-null  int64
 4   Fecha_Retiro           137354 non-null  datetime64[ns]
 5   Hora_Retiro            137354 non-null  object
 6   Ciclo_Estacion_Arribo  137354 non-null  int64
 7   Fecha_Arribo           137354 non-null  object
 8   Hora_Arribo            137354 non-null  object
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 10.5+ MB

### 2018

In [37]:
df_2018_1 = pd.read_csv('DATOS/2018-03.csv', low_memory=False)
df_2018_2 = pd.read_csv('DATOS/2018-04.csv', low_memory=False)

In [42]:
df_2018_1.head(2)

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_Estacion_Arribo,Fecha_Arribo,Hora_Arribo
0,M,49,3307,365,01/03/2018,0:00:10,169,01/03/2018,0:13:05
1,F,29,9218,137,01/03/2018,0:00:13,308,01/03/2018,0:18:34

In [43]:
df_2018_2.head(2)

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_Estacion_Arribo,Fecha_Arribo,Hora_Arribo
0,M,44,6851,69,01/04/2018,0:02:20,121,01/04/2018,0:09:34
1,M,39,3826,144,01/04/2018,0:02:46,145,01/04/2018,0:07:10

In [46]:
df_2018_1['Fecha_Retiro'] = pd.to_datetime(df_2018_1['Fecha_Retiro'], format='%d/%m/%Y', errors='coerce')
df_2018_1 = df_2018_1[((df_2018_1['Fecha_Retiro'] >= pd.Timestamp('2018-03-25')) & (df_2018_1['Fecha_Retiro'] <= pd.Timestamp('2018-04-01')))]

In [48]:
df_2018_2['Fecha_Retiro'] = pd.to_datetime(df_2018_2['Fecha_Retiro'], format='%d/%m/%Y', errors='coerce')
df_2018_2 = df_2018_2[((df_2018_2['Fecha_Retiro'] >= pd.Timestamp('2018-03-25')) & (df_2018_2['Fecha_Retiro'] <= pd.Timestamp('2018-04-01')))]

In [50]:
df_2018 = pd.concat([df_2018_1, df_2018_2])

In [52]:
df_2018.info()

<class 'pandas.core.frame.DataFrame'>
Index: 135293 entries, 612232 to 68581
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Genero_Usuario         135293 non-null  object
 1   Edad_Usuario           135293 non-null  int64
 2   Bici                   135293 non-null  object
 3   Ciclo_Estacion_Retiro  135293 non-null  int64
 4   Fecha_Retiro           135293 non-null  datetime64[ns]
 5   Hora_Retiro            135293 non-null  object
 6   Ciclo_Estacion_Arribo  135293 non-null  int64
 7   Fecha_Arribo           135293 non-null  object
 8   Hora_Arribo            135293 non-null  object
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 10.3+ MB

In [54]:
del df_2018_1
del df_2018_2

### 2019

In [57]:
df_2019 = pd.read_csv('DATOS/2019-04.csv', low_memory=False)

In [58]:
df_2019.head(2)

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_Estacion_Arribo,Fecha_Arribo,Hora_Arribo
0,M,28,2388,378,01/04/2019,00:00:06,323,01/04/2019,00:09:01
1,M,27,8272,309,01/04/2019,00:00:09,288,01/04/2019,00:03:13

In [59]:
df_2019['Fecha_Retiro'] = pd.to_datetime(df_2019['Fecha_Retiro'], format='%d/%m/%Y', errors='coerce')
df_2019 = df_2019[((df_2019['Fecha_Retiro'] >= pd.Timestamp('2019-04-14')) & 
                       (df_2019['Fecha_Retiro'] <= pd.Timestamp('2019-04-21')))]

In [60]:
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
Index: 127573 entries, 354242 to 538369
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Genero_Usuario         127573 non-null  object
 1   Edad_Usuario           127573 non-null  int64
 2   Bici                   127573 non-null  int64
 3   Ciclo_Estacion_Retiro  127573 non-null  int64
 4   Fecha_Retiro           127573 non-null  datetime64[ns]
 5   Hora_Retiro            127573 non-null  object
 6   Ciclo_Estacion_Arribo  127573 non-null  int64
 7   Fecha_Arribo           127573 non-null  object
 8   Hora_Arribo            127573 non-null  object
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 9.7+ MB

### 2020

In [66]:
df_2020 = pd.read_csv('DATOS/2020-04.csv', low_memory=False)

In [67]:
df_2020.head()

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_Estacion_Arribo,Fecha_Arribo,Hora_Arribo
0,M,33,9098,70,31/03/2020,23:31:41,172,01/04/2020,00:00:13
1,M,25,8870,321,31/03/2020,23:55:25,342,01/04/2020,00:01:32
2,M,25,8870,321,31/03/2020,23:55:25,451,01/04/2020,00:02:10
3,M,35,7614,221,31/03/2020,23:56:59,223,01/04/2020,00:02:42
4,M,31,11274,405,31/03/2020,23:44:45,405,01/04/2020,00:03:04

In [68]:
df_2020['Fecha_Retiro'] = pd.to_datetime(df_2020['Fecha_Retiro'], format='%d/%m/%Y', errors='coerce')
df_2020 = df_2020[((df_2020['Fecha_Retiro'] >= pd.Timestamp('2020-04-05')) & 
                       (df_2020['Fecha_Retiro'] <= pd.Timestamp('2020-04-12')))]

In [72]:
df_2020.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35172 entries, 24098 to 125042
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Genero_Usuario         35091 non-null  object
 1   Edad_Usuario           35172 non-null  int64
 2   Bici                   35172 non-null  object
 3   Ciclo_Estacion_Retiro  35172 non-null  int64
 4   Fecha_Retiro           35172 non-null  datetime64[ns]
 5   Hora_Retiro            35172 non-null  object
 6   Ciclo_Estacion_Arribo  35172 non-null  int64
 7   Fecha_Arribo           35172 non-null  object
 8   Hora_Arribo            35172 non-null  object
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 2.7+ MB

In [73]:
df_2020.head(2)

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_Estacion_Arribo,Fecha_Arribo,Hora_Arribo
24098,M,30,8851,12,2020-04-05,00:04:11,6,05/04/2020,00:09:39
24101,M,47,11598,121,2020-04-05,00:06:48,53,05/04/2020,00:16:01

### Parte IAN

In [118]:
df_ian = pd.read_csv('DATOS/IAN.txt')

C:\Users\ricro\AppData\Local\Temp\ipykernel_31724\3858631990.py:1: DtypeWarning: Columns (3,6,7,8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ian = pd.read_csv('DATOS/IAN.txt')

In [119]:
df_ian['Fecha_Retiro'].unique()

array(['2021-03-28', '2021-03-29', '2021-03-30', '2021-03-31',
       '2021-04-01', '2021-04-02', '2021-04-03', '2021-04-04',
       '2022-04-12', '2022-04-13', '2022-04-11', '2022-04-14',
       '2022-04-17', '2022-04-10', '2022-04-15', '2022-04-16',
       '2023-04-02', '2023-04-03', '2023-04-04', '2023-04-05',
       '2023-04-06', '2023-04-07', '2023-04-08', '2023-04-09',
       '2024-03-24', '2024-03-25', '2024-03-26', '2024-03-27',
       '2024-03-28', '2024-03-29', '2024-03-30', '2024-03-31',
       '2025-04-13', '2025-04-14', '2025-04-15', '2025-04-16',
       '2025-04-17', '2025-04-18', '2025-04-19', '2025-04-20'],
      dtype=object)

In [120]:
df_ian.head(2)

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_EstacionArribo,Fecha Arribo,Hora Arribo,Hora_Arribo,Fecha_Arribo
0,M,46.0,12387.0,277.0,2021-03-28,12:02:51,164.0,2021-03-28 00:00:00,12:09:39,NaN,NaN
1,M,49.0,9013.0,308.0,2021-03-28,12:03:50,347.0,2021-03-28 00:00:00,12:09:46,NaN,NaN

In [121]:
df_ian.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1141254 entries, 0 to 1141253
Data columns (total 11 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Genero_Usuario         1124416 non-null  object
 1   Edad_Usuario           1141211 non-null  float64
 2   Bici                   1141254 non-null  float64
 3   Ciclo_Estacion_Retiro  1141254 non-null  object
 4   Fecha_Retiro           1141254 non-null  object
 5   Hora_Retiro            1141254 non-null  object
 6   Ciclo_EstacionArribo   1141254 non-null  object
 7   Fecha Arribo           773282 non-null   object
 8   Hora Arribo            370261 non-null   object
 9   Hora_Arribo            770993 non-null   object
 10  Fecha_Arribo           367972 non-null   object
dtypes: float64(2), object(9)
memory usage: 95.8+ MB

In [122]:
df_ian = df_ian.rename(columns = {'Ciclo_EstacionArribo': 'Ciclo_Estacion_Arribo'})

In [123]:
df_ian = df_ian[['Ciclo_Estacion_Retiro', 'Fecha_Retiro', 'Ciclo_Estacion_Arribo']]

In [130]:
df_ian['Fecha_Retiro'] = pd.to_datetime(df_ian['Fecha_Retiro'])

In [132]:
df_ian.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1141254 entries, 0 to 1141253
Data columns (total 3 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Ciclo_Estacion_Retiro  1141254 non-null  object
 1   Fecha_Retiro           1141254 non-null  datetime64[ns]
 2   Ciclo_Estacion_Arribo  1141254 non-null  object
dtypes: datetime64[ns](1), object(2)
memory usage: 26.1+ MB

### Uniendo el df en uno solo

In [135]:
df = pd.concat([df_2015, df_2016, df_2017, df_2018, df_2019, df_2020])
df = df[['Ciclo_Estacion_Retiro', 'Fecha_Retiro', 'Ciclo_Estacion_Arribo']]
df = pd.concat([df, df_ian])

In [137]:
df.head(2)

       Ciclo_Estacion_Retiro Fecha_Retiro Ciclo_Estacion_Arribo
744480                    52   2015-03-29                    35
744481                    52   2015-03-29                    35

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1826702 entries, 744480 to 1141253
Data columns (total 3 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Ciclo_Estacion_Retiro  object
 1   Fecha_Retiro           datetime64[ns]
 2   Ciclo_Estacion_Arribo  object
dtypes: datetime64[ns](1), object(2)
memory usage: 55.7+ MB

In [141]:
df_ian['Fecha_Retiro'].unique()

<DatetimeArray>
['2021-03-28 00:00:00', '2021-03-29 00:00:00', '2021-03-30 00:00:00',
 '2021-03-31 00:00:00', '2021-04-01 00:00:00', '2021-04-02 00:00:00',
 '2021-04-03 00:00:00', '2021-04-04 00:00:00', '2022-04-12 00:00:00',
 '2022-04-13 00:00:00', '2022-04-11 00:00:00', '2022-04-14 00:00:00',
 '2022-04-17 00:00:00', '2022-04-10 00:00:00', '2022-04-15 00:00:00',
 '2022-04-16 00:00:00', '2023-04-02 00:00:00', '2023-04-03 00:00:00',
 '2023-04-04 00:00:00', '2023-04-05 00:00:00', '2023-04-06 00:00:00',
 '2023-04-07 00:00:00', '2023-04-08 00:00:00', '2023-04-09 00:00:00',
 '2024-03-24 00:00:00', '2024-03-25 00:00:00', '2024-03-26 00:00:00',
 '2024-03-27 00:00:00', '2024-03-28 00:00:00', '2024-03-29 00:00:00',
 '2024-03-30 00:00:00', '2024-03-31 00:00:00', '2025-04-13 00:00:00',
 '2025-04-14 00:00:00', '2025-04-15 00:00:00', '2025-04-16 00:00:00',
 '2025-04-17 00:00:00', '2025-04-18 00:00:00', '2025-04-19 00:00:00',
 '2025-04-20 00:00:00']
Length: 40, dtype: datetime64[ns]

In [143]:
df.to_csv('DATOS/datos_limpios.csv', index = False)